// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQl4XSF88a2qBjFg_RydDFxIBSo0oqUzU',
    appId: '1:744653600839:web:2840f06ab3405616539962',
    messagingSenderId: '744653600839',
    projectId: 'bloodalert-3ce3b',
    authDomain: 'bloodalert-3ce3b.firebaseapp.com',
    databaseURL: 'https://bloodalert-3ce3b-default-rtdb.firebaseio.com',
    storageBucket: 'bloodalert-3ce3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMKjccBnKteNP5ORHCU5V2DIZHwAutkeQ',
    appId: '1:744653600839:android:420bc50ca5d3dcad539962',
    messagingSenderId: '744653600839',
    projectId: 'bloodalert-3ce3b',
    databaseURL: 'https://bloodalert-3ce3b-default-rtdb.firebaseio.com',
    storageBucket: 'bloodalert-3ce3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_vguAI6PurL0FZ4tV4F6DNF46ON8zeNs',
    appId: '1:744653600839:ios:853cd04cb9aa2dd3539962',
    messagingSenderId: '744653600839',
    projectId: 'bloodalert-3ce3b',
    databaseURL: 'https://bloodalert-3ce3b-default-rtdb.firebaseio.com',
    storageBucket: 'bloodalert-3ce3b.appspot.com',
    iosClientId: '744653600839-ue1stn9v20rrfcugs2k8nkgb7a9570nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_vguAI6PurL0FZ4tV4F6DNF46ON8zeNs',
    appId: '1:744653600839:ios:853cd04cb9aa2dd3539962',
    messagingSenderId: '744653600839',
    projectId: 'bloodalert-3ce3b',
    databaseURL: 'https://bloodalert-3ce3b-default-rtdb.firebaseio.com',
    storageBucket: 'bloodalert-3ce3b.appspot.com',
    iosClientId: '744653600839-ue1stn9v20rrfcugs2k8nkgb7a9570nu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodAlert',
  );
}
