// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7zDpQpW7pEgG9uHxoSwDl7aQXV_2drs',
    appId: '1:693560897326:web:f2514a66053d8b11df14bf',
    messagingSenderId: '693560897326',
    projectId: 'bloodalert-190db',
    authDomain: 'bloodalert-190db.firebaseapp.com',
    storageBucket: 'bloodalert-190db.appspot.com',
    measurementId: 'G-MNCQNBDS8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ9cNb3StruuMF-ys7EdEgx7PSuqtNwzE',
    appId: '1:693560897326:android:6de3e1e31674668fdf14bf',
    messagingSenderId: '693560897326',
    projectId: 'bloodalert-190db',
    storageBucket: 'bloodalert-190db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf2mWBo8wkjelQupOcGITG4-i0572j2M0',
    appId: '1:693560897326:ios:c7c5e30e5c70759fdf14bf',
    messagingSenderId: '693560897326',
    projectId: 'bloodalert-190db',
    storageBucket: 'bloodalert-190db.appspot.com',
    iosClientId: '693560897326-b4siqlvk8cm969551ddmi81gep84n0ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf2mWBo8wkjelQupOcGITG4-i0572j2M0',
    appId: '1:693560897326:ios:c7c5e30e5c70759fdf14bf',
    messagingSenderId: '693560897326',
    projectId: 'bloodalert-190db',
    storageBucket: 'bloodalert-190db.appspot.com',
    iosClientId: '693560897326-b4siqlvk8cm969551ddmi81gep84n0ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodAlert',
  );
}
